# Generated by Django 4.2.3 on 2023-08-17 09:28

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("Logo", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="car",
            fields=[
                ("Owner_name", models.CharField(max_length=50, null=True)),
                (
                    "Chasis_no",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="engine",
            fields=[
                (
                    "Engine_no",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Engine_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("Role", models.CharField(max_length=50, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="showroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                ("Location", models.CharField(max_length=50)),
                ("contact", models.EmailField(max_length=254, null=True)),
                ("Owner", models.CharField(max_length=50)),
                ("Staff", models.ManyToManyField(to="Showroom.staff")),
            ],
        ),
        migrations.CreateModel(
            name="model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "images",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            location=pathlib.PureWindowsPath(
                                "D:/code files/aws_mzr/Django/(5) Django forms/media"
                            )
                        ),
                        upload_to="",
                    ),
                ),
                ("Car_price", models.IntegerField(max_length=50, null=True)),
                ("Year_model", models.DateField(default=None, null=True)),
                ("Publish_date", models.DateField(auto_now=True, null=True)),
                ("Engine_name", models.CharField(max_length=50, null=True)),
                (
                    "Brand",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="Showroom.brand",
                    ),
                ),
                (
                    "Chasis_number",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Showroom.car",
                    ),
                ),
                (
                    "Engine_number",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_model",
                        to="Showroom.engine",
                    ),
                ),
                (
                    "Features",
                    models.ManyToManyField(
                        related_name="models", to="Showroom.feature"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="engine",
            name="model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="model",
                to="Showroom.engine_model",
                verbose_name="Engine model name",
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="showrooms",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Showroom.showroom",
            ),
        ),
    ]
