# Generated by Django 4.2.3 on 2023-08-22 09:07

import django.core.files.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ("Showroom", "0002_alter_model_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="Chasis_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="model",
            name="images",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location=pathlib.PureWindowsPath(
                        "D:/code files/aws_mzr/Django/(8) Showroom and blog website together/media"
                    )
                ),
                upload_to="",
            ),
        ),
    ]
