# Generated by Django 4.2.3 on 2023-08-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Showroom", "0003_alter_model_chasis_number_alter_model_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="Chasis_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
