# Generated by Django 4.2.3 on 2023-08-22 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Showroom", "0004_alter_model_chasis_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="Chasis_number",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Showroom.car",
            ),
        ),
    ]
